### ISSUE TITLE
How does the root field get set?

### ISSUE THREAD

**Issue by aronhoyer** [hcavalieri/gatsby-source-sanity#1]
Given a `queries` array…
```
queries: [
  {
    name: 'movies',
    groq: `
      *[_type == 'movie']{
        _id,
        title
      }
    `
  },
]
```
…what would the root field get set as?

A query…
```
<StaticQuery
  query={graphql`
    query {
      SanityMovies {
        …
      }
    }
  `}
  …
```
…just returns `GraphQL Error Unknown field 'SanityMovies' on type 'Query'`

Kinda missing an example in docs, as it's not really that intuitive when you first get into it.

**Comment by aronhoyer** [comment]
Evidently `'Sanity' + query.name` is incorrect. It _should_ be `'sanity'+query.name` camelCased. I.e. `sanityMovies`.

**Comment by hcavalieri** [comment]
Hey there, @aronhoyer !

So, the final `type` generated by the plugin is `Sanity${capitalizeFirstLetter(query.name)}`, but when Gatsby creates the GraphQl schema, it generates `sanity${capitalizeFirstLetter(query.name)}` and `AllSanity${capitalizeFirstLetter(query.name)}`, so that's how you should access it! Take a look at the image below:

![image](https://user-images.githubusercontent.com/27744332/43985076-06e1452a-9cdb-11e8-961b-10531d29a3ad.png)

**To avoid this confusion** you can always **use your own defined `type`**, just include `type: Movies` in your query object and voilà! (this is what I've done with the `home` query in the picture above)

_PS_: I've updated the documentation to ask people to investigate the GraphiQl interface (localhost:8000/___graphql) before using queries to understand the generated data structure, this might hopefully help you next time ;)
