### ISSUE TITLE
GraphQL and Sanity blocks nightmare

### ISSUE THREAD

**Issue by Yago** [hcavalieri/gatsby-source-sanity#3]
When you are using [blocks](https://www.sanity.io/docs/schema-types/block-type) to provide rich content to your Sanity editing experience, it produces a large amount of raw nested data. When with GROQ, it's easy to retrieve, GraphQL is another story.

If the GROQ query look like : 
```js
groq: `
*[_type == 'article']{
  _id,
  title,
  article_body
}
`
```

Your Gatsby GraphQL query will look like : 
```js
export const query = graphql`
  query articleQuery($slug: String!) {
    article(slug: { current: { eq: $slug } }) {
      id
      title
      article_body {
        _key
        _type
        style
        markDefs {
          _key
          _type
          href
        }
        children {
          _key
          _type
          text
          marks
        }
      }
    }
  }
`;
```

The structured sub-fields are not constant and depend on the content. For example, `markDefs` or even `marks` are not always here for very simple typed content. So we cannot predict the exact schema of this query...

I use `@sanity/block-content-to-react` to render the block field, but it needs every sub-fields nested below.

@hcavalieri Have you already encountered this case and/or have you some kind of solution ?

**Comment by hcavalieri** [comment]
Hey there, @Yago !

I've actually came across this at multiple points in time, and I know 2 ways of fixing this: you either use **functions and conditionals inside your query** to provide fallback values for the unused parts of the block content, or - and this is the one I use - create a **document that contains every possible combination** and element in a block field. Then, save the doc's ID and do a conditional in `gatsby-node.js` to avoid creating a page for this specific document, and voilà: it won't affect the website but will provide you with a surefire way to populate your GraphQL schema!

Then, you can query the whole block content (and this will be a tedious process of opening `localhost:800/___graphiql` and hitting `CTRL + SPACE`) and treat the block field before adding it to `@sanity/block-content-to-react`: this consists of providing an empty array for `markDefs` and `marks` in case they're empty, as GraphQL will return `null` instead of `[]` in this case. You can create a simple reusable component if you go through this very often.

I don't have much time right now to do a thorough tutorial, but I intend to get deeper into this later, maybe writing a guide on this repo or recording a video tutorial :wink:

**Comment by Yago** [comment]
Thank you for the detailed answer @hcavalieri !

I have thought of some kind of solution that can be implemented in `gatsby-source-sanity`. The idea is to flag the rich content fields using the renaming feature of GROQ and process them before creating the Gatsby node.

It will look a bit like : 

```js
groq: `
*[_type == 'article']{
  _id,
  title,
  "article_body_toString": article_body
}
`
```

in `src/gatsby-node.js` : 
```js
const finalNodeSanitized = recursiveMethod(finalNode, (key, value) => { 
 if (key.includes('_toString')) return JSON.stringify(value);
 return value;
});

createNode({...
```

How those it sound ? It will decrease the size of Gatsby GraphQL queries by removing all the block generated subfields and we can `JSON.parse` this value right before feeding the `@sanity/block-content-to-react`. 

I know it's a bit of a hack 😅 But if it speaks to you, I can do a PR 😉

**Comment by hcavalieri** [comment]
Sorry for the wait, @Yago ! I spent the weekend thinking about how simple and smart your solution is, but didn't have the time / priority to test it hahaha

You can go ahead and do a PR on this and I'll publish to npm ;) Just a quick consideration: I believe this would be best under an optional parameter sent inside the plugin configuration such as `stringifyPattern: '_toString'` that, when undefined, wouldn't stringify anything and, when defined (it should be a string), we'd run `key.includes(stringifyPattern)`. This way we give more flexibility to users...

Oh, and the code is a bit unruly, feel free to refactor whatever you want, feedback is welcome :smile:

**Comment by Yago** [comment]
Done ! Thank you for your open-mindedness and your ideas. Feel free to do any kind of feedbacks 😉

**Comment by hcavalieri** [comment]
#4 solves this problem with Yago's smart solution, issue solved :smile:

**Comment by kupe517** [comment]
@hdoro @Yago Could one of you provide some example code of how to use the solution? I'm not sure how to format my GraphQL query with a block, or what needs to happen in gatsby-node. Thanks!
